# vim: set ts=2 et:

jobs:
  include:

    # Pipenv Python 3.7.5 + QT5 - Build .app
    - os: osx
      language: generic
      env:
        - PIPENV_VENV_IN_PROJECT=1
        - PIPENV_IGNORE_VIRTUALENVS=1
      install:
        - python3 --version
        - pip3 install pipenv
        - pipenv install pyqt5 lxml
        - pipenv run pip install pyqt5==5.13.2 lxml
        - pipenv run make qt5py3
        - rm -rf build dist
        - pipenv run python setup.py py2app
        - open dist/labelImg.app

script:
  - exit 0
